baseURL 		= 'http://example.org/'
languageCode 	= 'en-us'
title 			= 'Sjmelcks first Hugo site!'
theme 			= "ananke"
paginate 		= 10
publishDir 		= "docs" 
Copyright 		= "© Balshaw, RC and Marx, DG (2022)"